/*
 * Fault.c
 *
 *  Created on: Apr 29, 2022
 *      Author: Truong
 */


/*
 * Fault.c
 *
 *  Created on: Apr 29, 2022
 *      Author: Truong
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
    //1.enable all configurable exception like usage fault,bus fault , memory managed fault
	uint32_t *pSHCSR = (uint32_t *)0xE000ED24;

	*pSHCSR |= (1 << 18);
	*pSHCSR |= (1 << 17);
	*pSHCSR |= (1 << 16);


	uint32_t *pSRAM = (uint32_t *)0x20010000;
	*pSRAM = 0xFFFFFFFF;

	void (*some_address)(void);

	some_address = (void* )((uint32_t)pSRAM + 1);

	some_address();
	//3.implement undefined instruction


	//4. analyze the fault


}

//2.implement the fault handler

void HardFault_Handler()
{
	printf("in this hard fault \n");
	while(1);
}

void MemManage_Handler()
{
	printf("in memory managed handler \n");
	while(1);
}

void BusFault_Handler()
{
	printf("in this bus fault \n");
	while(1);
}

void UsageFault_Handler()
{
	uint32_t *pUFSR = (uint32_t *)0xE000ED2A;
	printf("in usage handler \n");
	printf("UFSR = %lx \n",(*pUFSR) & 0xFFFF);
	while(1);
}


